// GENERATED BY webrogue-event-apigen. DO NOT EDIT MANUALLY
#include <stddef.h>
#include <stdint.h>

void webrogue_gfx_present();
void webrogue_gfx_make_window();
void webrogue_gfx_window_size(int *width, int *height);
void webrogue_gfx_gl_size(int *width, int *height);
void webrogue_gfx_init_gl();
void *webrogueGLLoader(const char *procname);

// Events
struct webrogue_event_mouse {
    uint32_t x;
    uint32_t y;
};
enum webrogue_event_type {
    webrogue_event_type_invalid = 0,
    webrogue_event_type_mouse = 1,
};
typedef struct webrogue_event {
    enum webrogue_event_type type;
    union {
        struct webrogue_event_mouse mouse;
    } inner;
} webrogue_event;

webrogue_event webrogue_gfx_poll();
